name: Secret Demo

on:
  workflow_dispatch:

jobs:
  secret-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret
        env:
          DEMO_MESSAGE: ${{ secrets.DEMO_MESSAGE }}
        run: |
          if [ -n "$DEMO_MESSAGE" ]; then
            echo "Secret is available."
          else
            echo "Secret is missing."
            exit 1
          fi